### ISSUE TITLE
Add values to existing search parameter

### ISSUE THREAD

**Issue by sashakru** [ReactTraining/history#460]
Hello there,

I have url that looks like `www.myUrl.com?filters=id_1`,

when I select additional filter in my app I would like to do something like this
```
history.push({search: '?filters=id_2', addIfExisting: true});
```
as expected result I want get: `www.myUrl.com?filters=id_1,id_2`, but actual result is: `www.myUrl.com?filters=id_2`

is there any build in functionality for this case?

**Comment by tcclevela** [comment]
@sashakru this is the expected behavior. As you can see in the source [here](https://github.com/ReactTraining/history/blob/master/modules/PathUtils.js#L39-L51) any url generated from that location just takes the literal search string and appends it. I would recommend using some simple conversion methods to do this kind of logic eg with `stringifyQueryObj` which could take an object and return a query string and `parseQueryString`, which would take a query string and convert it to an object:

```
const updateFilter = (currentQueryString, updatedQuery) => {
  const currentQuery = parseQueryString(currentQueryString);
  return stringifyQueryObj({
    ...currentQuery,
    ...updatedQuery
  });
}
```
Which you could then use like this:
```
// assume you have `currentLocation`
const updatedSearch = updateFilter(currentLocation.search, {filters=['id_1', 'id_2']})"
history.push({pathname: 'www.myUrl.com', search: updatedSearch}}, 
```

**Comment by sashakru** [comment]
@tcclevela got it, thanks!

**Comment by mjackson** [comment]
Thanks @tcclevela :)

**Comment by tcclevela** [comment]
Yah np. :)
