### ISSUE TITLE
Query not being parsed in createPath

### ISSUE THREAD

**Issue by CaldwellYSR** [ReactTraining/history#521]
In the [React Router v4 docs](http://knowbody.github.io/react-router-docs/api/Link.html#to) it mentions that query is deprecated and should be passed to `to` as an object to be stringified. I can't get the `to` object to work correctly. It parses `pathname` but not `query`.

I chased the issue down from [React Router Link](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L71-L73) to [createBrowserRouterHistory](https://github.com/ReactTraining/history/blob/master/modules/createBrowserHistory.js#L151-L152) down to [PathUtils](https://github.com/ReactTraining/history/blob/master/modules/PathUtils.js#L40-L52) and it looks like `PathUtils` doesn't look for the `query` object to be passed in. I was going to create a PR but I canfigure out what this packages uses to stringify the query object.

**Comment by pshrmn** [comment]
The `search` string property of `location` objects instead of `query` objects is completely intentional (the location object is meant to replicate the properties of the [Location](https://developer.mozilla.org/en-US/docs/Web/API/Location) object). I don't think that that is going to change any time soon.

That means that turning a query object into a string (and vice versa) is left completely to the user. You can use [qs](https://www.npmjs.com/package/qs), [querystring](https://www.npmjs.com/package/querystring), [query-string](https://www.npmjs.com/package/query-string), [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) or any other package/native code.

**Comment by CaldwellYSR** [comment]
I suppose that means the [React Router 4 Docs](http://knowbody.github.io/react-router-docs/api/Link.html#to) are wrong? I have parsed the query and renamed it to "search" instead of query but that goes against what it says in the docs.

**Comment by pshrmn** [comment]
Those are not the v4 docs. You can view the v4 documentation [here](https://reacttraining.com/react-router/).

**Comment by mjackson** [comment]
Thanks, @pshrmn. Closing.
