### ISSUE TITLE
Creating `query` object without prototype.

### ISSUE THREAD

**Issue by PepijnSenders** [ReactTraining/history#525]
Hey there!

Thanks for writing this amazing library 😸 (we're using **v3** btw)

Today we ran into an issue where a debugging tool we use couldn't parse an action object that was sent through `react-router-redux`. After some debugging, we found out that this object was the `location` object from this library.

The debugging tool uses [hasOwnProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) recursively and when it passes through the object it finds the `query` object at some point.

So apparently this library creates the `query` object without `prototype` on purpose as I find out [here](https://github.com/ReactTraining/history/blob/v3/modules/LocationUtils.js#L7). Is there still a reason for this? Can this be reverted to an actual object? Or is this not possible. It's kind of sad that we would have to reparse only this object in our event stream, so it would be nice if this could be fixed on a library level.

Thanks!

Best,
Pepijn

**Comment by mjackson** [comment]
The reason we need to use a blank object here is to avoid false positives when checking for values that were in the query string. For example, if you had any property in the query string that was also the name of an `Object` property or method, this could cause some unexpected behavior.

```js
const paramName = 'valueOf'

if (location.query[paramName]) {
  // ...
}
```

Perhaps you could modify the debugging tool to use `Object.getOwnPropertyNames` instead of `Object.prototype.hasOwnProperty`? That would be more safe.

**Comment by PepijnSenders** [comment]
Hey @mjackson, thanks for responding. 

Firstly the debugging tool we use is not ours, it's GTM's and we send this event through our dataLayer.

Secondly, I don't really understand your point though if the `key` that you set has the same name as an object method the key you set will persevere.

Example:

```js
const query = { valueOf: 'test' }

console.log(query['valueOf']) // test
```

Or am I not seeing something?
