### ISSUE TITLE
getCurrentLocation() inside listenBefore() is already the updated location

### ISSUE THREAD

**Issue by amarinov** [ReactTraining/history#581]
Hi all! First of all, I would like to **thank you** for the work you're doing. Your help is highly appreciated. And now here's the problem:

Since I'm using react-router v3, I'm stuck with history v3. Based on my research, there's no way to actually get the previous location once you've transitioned, so here's what I'm doing:

```
        browserHistory.listenBefore(nextLocation => {
            const currentLocation = browserHistory.getCurrentLocation();

            if (nextLocation.pathname !== currentLocation.pathname) {
                pendingPreviousPathname = currentLocation.pathname;
                pendingNextPathname = nextLocation.pathname;
            } else {
                pendingPreviousPathname = pendingNextPathname = undefined;
            }

        });

        browserHistory.listen(currentLocation => {
            if (pendingNextPathname === currentLocation.pathname) {
                previousPathname = pendingPreviousPathname;
            }
        });
```

It's a workaround for the missing API for it, but it works fine, **except for the case when you click BACK using the browser navigation**. Then getCurrentLocation() inside the listenBefore hook is already the location you're supposed to catch before the transition (nextLocation.pathname === currentLocation.pathname).

That doesn't seem expected, as one would try to hook into the transition **before it happens**. Any suggestions/thoughts?

**Comment by pshrmn** [comment]
@amarinov This is related to how `history` detects back/forward button clicks. These can only be detected through a `popstate` event listener, so `history` doesn't actually know the browser has changed locations until after it has happened.

[When you call `getCurrentLocation`, it is just reading from `window.location`](https://github.com/ReactTraining/history/blob/v3/modules/BrowserProtocol.js#L21-L40). Since the browser has already updated the location, it is reading that.

Unfortunately, there isn't a way to override the `getCurrentLocation` implementation. I think that I would recommend just storing the current location yourself and referencing that value in your `listenBefore` observer.

```js
let currentLocation;
browserHistory.listenBefore(nextLocation => {
  // run any checks
  // then set the next currentLocation
  currentLocation = nextLocation
})
```

**Comment by amarinov** [comment]
Thanks, @pshrmn !
