### ISSUE TITLE
state undefined

### ISSUE THREAD

**Issue by chinadbo** [ReactTraining/history#591]
when I 
```javascript
let history = createhashHistory.default()
history.push({ pathname: '/login', search: `?from=${history.location.pathname}`, state: {some: 'state'} })
```
But
state is undefined!!!
![image](https://user-images.githubusercontent.com/4602050/40698499-db0e6c28-6401-11e8-91b2-7dea4f1c11c0.png)

**Comment by pshrmn** [comment]
Location state relies on the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) to set state for a location in the browser's history session. Hash history does not have `state` because it does not use the History API. Instead, it uses `window.location` to replace/push new locations.

**Comment by chinadbo** [comment]
I see .... Thank you
