### ISSUE TITLE
Update search by merging an object

### ISSUE THREAD

**Issue by Okazari** [ReactTraining/history#618]
Hi !

I'm currently using history in my stack (along with react, its router and redux, but that doesn't matter here)
I have a page where i update some search params according to my user actions on the UI.
Since `search` only takes a string in `history.push` and `history.replace` i had to manage it by myself.

I added a function i called `updateSearch` that is pretty naive **atm**.
```javascript
//signature

history.updateSearch({ foo: 1 })
//will do the following :
// myapp/                -> myapp/?foo=1
// myapp/?bar=2          -> myapp/?foo=1&bar=2
// myapp/?foo=2          -> myapp/?foo=1
// myapp/?foo=2&bar=2    -> myapp/?foo=1&bar=2

history.updateSearch({ foo: 1, bar: null })
//will do the following :
// myapp/                     -> myapp/?foo=1
// myapp/?bar=2               -> myapp/?foo=1
// myapp/?foo=2               -> myapp/?foo=1
// myapp/?foo=2&bar=2&yo=3    -> myapp/?foo=1&yo=3

history.updateSearch = (params) => {
  const currentParams = qs.parse(history.location.search, { ignoreQueryPrefix: true })
  const finalParams = pickBy({ ...currentParams, ...params }, value => value !== null)
  history.replace({
    search: `?${qs.stringify(finalParams)}`,
  })
}
```

Here is some questions :
 - Do you have a built in way to do so ? (Did i miss something ?)
 - If there is no built in way, do you think a function like this (**with some improvement**) is worth a **PR** ?

Thanks in advance !

**Comment by pshrmn** [comment]
@Okazari The current `history` implementation intentionally uses strings instead of objects for `history.search`. Unless something changes in that regard, there cannot be a built-in way to modify the `search`, so you didn't miss anything there.

Part of the reasoning behind `history` using strings instead of objects is to intentionally avoid choosing one of the many query parsing solutions for you, so I don't think that a PR that adds one of these packages would be accepted.

**Comment by Okazari** [comment]
@pshrmn Thanks for the heads on :)
