### ISSUE TITLE
Missing "modules.root" entry in package.json

### ISSUE THREAD

**Issue by felipeptcho** [ReactTraining/history#641]
Please check: https://github.com/ReactTraining/react-router/issues/5576#issuecomment-338150863

**Comment by mjackson** [comment]
[The modules spec](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md) does not require packages to have a `modules.root` field, so webpack should not be relying on this field to be present in order to work properly. Besides, we publish a single-file build now, so `modules.root` would not be necessary for us since there are no relative paths to resolve.
