### ISSUE TITLE
Can not change basename after initialization

### ISSUE THREAD

**Issue by KennyLindahl** [ReactTraining/history#644]
Same issue has been brought up before and is still not supported: https://github.com/ReactTraining/history/issues/188

Use case:
- Want to dynamically change the `basename` (language change):
    - `en/my-account`
    - `sv/my-account`
    - ...

Right now it looks like it's only possible to set it once and then the module will reuse the basename internally without any possibility of altering it:
```javascript
createBrowserHistory({
    basename: getLocale(), //en, sv, ...
})
```

And i can't use basename prop on the react router because that won't change the url from `/my-account` to `basename/my-account` automatically which this history package does.

Questions:
- Is it possible to do but i can't find any way to do it?
- Is it done by design to only make it possible to set basename upon init?
- Are you welcoming PRs to add this? If so, how do you recommend the API to look like?

Thanks in advance!

**Comment by pshrmn** [comment]
The `basename` should not be considered dynamic; its purpose is to identify an application's "root" on the server.

If a "basename" should be dynamic, one approach would be to use a route param. This isn't necessarily ideal because you would have to include the language param in every single link. A helper function (`<Link to={withLocale("/my-account")}>` where `withLocale` comes from a module that stores the current language and prepends it on the path) could help, but the situation definitely isn't ideal.

I think that a better solution would be to treat the different languages as different apps; if you want to navigate between two languages, that would be considered switching apps. With React Router, this would mean that if you want to switch from the English app to the Swedish app, you would use an anchor instead of a `Link` (`<a href="/sv/some-page">`).

**Comment by KennyLindahl** [comment]
@pshrmn Thanks for your answer.
Yes, i tried to do like this:
```javascript
createBrowserHistory({basename: '/:locale'})
```

But it never becomes a part of the pathname so i don't know how i could replace that part later on.

**Comment by pshrmn** [comment]
The `basename` is hard-coded and doesn't set params. To use params, you would use a root `Route` component.

```jsx
ReactDOM.render((
  <BrowserRouter>
    <Router path="/:locale" component={App} />
  </BrowserRouter>
), root);

function App({ match }) {
  const locale = match.path; // or match.url if your components do not need
  // access to the locale param
  return (
    <Switch>
      <Route exact path={`${locale}`} component={Home} />
      <Route exact path={`${locale}/my-account`} component={MyAccount} />
    </Switch>
  );
}

```

**Comment by KennyLindahl** [comment]
@pshrmn Thanks for the advice, but i've already considered that.
That would require manual manipulation of the URL and so on which i would prefer to make this module handle instead when setting basename.
