### ISSUE TITLE
Removing PathUtils seems like a breaking change, why no major version?

### ISSUE THREAD

**Issue by waynebloss** [ReactTraining/history#683]
~~Title says it all.~~

In `4.7.2` history/PathUtils was available. Now in version `4.9.0` it's not. This does not follow the semver contract.

Thanks!

**Comment by l0gicgate** [comment]
I agree, how is this acceptable for a minor release? Just broke my build when I updated.

**Comment by pshrmn** [comment]
The only functions from the `PathUtils` module that were public API were (and still are) `parsePath` and `createPath`.

The rest of the functions in `PathUtils` module were importable because of how multiple file packages work, but were never public API.

**Comment by renchap** [comment]
+1, I am using an external library that is importing from `history/PathUtils` and the new version breaks my app:
https://github.com/FormidableLabs/redux-little-router/blob/master/src/util/normalize-href.js#L4

**Comment by pshrmn** [comment]
@renchap I would recommend installing a pinned version of `history` (probably `4.7.2`), especially since `redux-little-router` is deprecated and unlikely to update its own deps.

**Comment by renchap** [comment]
Yes this is what I did, and I am planning to move away from `redux-little-router`. But removing those files are still a major change and should have triggered a major version bump, not a minor one.

If you look at the deprecation message that was included in the beta versions, it confirms that a major bump was intented:
https://github.com/ReactTraining/history/blob/465288b91859244d401103c079c058c0a2be5cb0/warnAboutDeprecatedCJSRequire.js#L31-L32

**Comment by waynebloss** [comment]
I like to explore the depths of what guides peoples decisions in detail so I can learn. If you're in charge of the versioning, would you mind answering any or all of these postmortem questions @pshrmn ?

1. What problem was solved by not going to a new major version? (Or, what was the problem with going to a new version?)

2. Is there any technical, social or other underlying necessity being fulfilled here by following a standard that says "programmers must never use a module that was exported and unofficially documented, but not specifically marked as public"?

3. Should NPM version numbers dictate API-level compatibility or package-level compatibility? Which one is actually the standard here?

4. What problems might have been reduced by incrementing the new major version number?

If anyone else wants to chime in, I'd love your input. Thanks.

**Comment by pshrmn** [comment]
@waynebloss I wasn't the one that made the decision, but, while recognizing that it is inconvenient for some people, I also agree with it. I don't believe that a package has any responsibility to maintain access to non-public API.

With the new single-file build, we can explicitly limit exports to the public API, but what if we think about a private API breaking change with multiple module packages. For example, what if the `PathUtils.js` module was renamed to `path-utils.js`? This would have no effect on someone that is using the public API, but would be breaking for anything that expects `history/PathUtils` to exist. Would we have to make a major version bump for that?

Now, it was recommended to access some of the public API directly through their modules. For example, `import createBrowserHistory from "history/createBrowserHistory";`. This API still exists (albeit with a warning) because it was, technically, public API. This was mostly because tree-shaking (and its ilk) were pretty bad, so directly accessing the module could shrink bundle sizes. Most bundlers are better at tree-shaking, which is why we can switch to a single file build.

**Comment by mjackson** [comment]
Sorry, but we never recommended anyone use `history/PathUtils` as public API. The only public API that we ever released and documented are `parsePath` and `createPath`, which are still available on [our top-level exports](https://github.com/ReactTraining/history/blob/8101f9f7c77e6403dad9aaa7e7ba76a2422f6a73/modules/index.js#L5).
