### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by EricTousignant** [ReactTraining/history#688]
The way you are announcing the deprecation is extremely annoying when I'm trying to develop my app. This should only show up if the deprecated code is actually executed.

![image](https://user-images.githubusercontent.com/2239084/55033728-21d41700-4fea-11e9-8845-d71dc77511eb.png)

**Comment by EricTousignant** [comment]
No comments? Anything?

**Comment by StringEpsilon** [comment]
@EricTousignant:

>  This should only show up if the deprecated code is actually executed.

Well, it is executed. The way you import ```createHashHistory``` (or ```createBrowserHistory``` respectively) will be depreciated in a future release. As the warnings explain

There is no really good way to issue depreciation warnings on imports like that. 

You probably have one of the followin in your code:

```js
const createHashHistory = require("history/createHashHistory"); // will be depreciated
import createHashHistory from "history/createHashHistory"; // will be depreciated
```

Or you might have a tool in your build-chain that replaces ordinary imports with "direct imports" to aid treeshaking. Those might also cause this warning to appear. 

If you have a better way of issuing this warning, maybe submit a PR. Or at least provide the idea here so that someone else can give it a go.

**Comment by EricTousignant** [comment]
Thanks for leaving a better explanation. Well, as you said, it probably is a tool in my build chain (in this case react-admin), but I was overriding the history with my custom object, called using the correct way. So I was not expecting the tool to call it anymore. I guess this is too far down the rabbit hole of imports.

Would there be a way to set a global environment config to disable a specific deprecation message, so that I can continue working without have this message all the time? Or would that be too much work for little benefit?

Thank you very much.

**Comment by StringEpsilon** [comment]
You could force NPM to resolve history to 4.7.2 in your package.json:

``` json
  "resolutions": {
    "history": "4.7.2"
  }
```

Other than that, you'd have to wait for react-admin to fix the import statements on their end.

**Comment by EricTousignant** [comment]
Thanks! I will try that next Monday.
