### ISSUE TITLE
Error when pathname does not contain basename

### ISSUE THREAD

**Issue by manisha2012** [ReactTraining/history#694]
Given a history with a basename:

> const history = createBrowserHistory({ basename: '/base' })

When the history gets the location from the URL, it will strip the basename off of the pathname.

> if (basename)
>   path = stripPrefix(path, basename)

This means that a pathname without the basename is treated the same as a pathname with the basename.

> "/base/my-page" == "/my-page"

But this should not be the case. It should throw error 404, when there is no basename in the url.

Here's my code sample :

```
<BrowserRouter basename="/base1">
        <Route exact strict path="/" component={Home} />
</BrowserRouter>
```
Now If I type the url as "localhost:3000/base1/", then it's rendering Home component (as expected), but when I type the url as "localhost:3000/", then also it's rendering Home component with a warning "You are attempting to use a basename on a page whose URL has no basename.". 
I want that it should throw 404 error instead of warning, when there's no basename.

**Comment by pshrmn** [comment]
This is happening because your development server is serving your application for every endpoint. In production, the server should only serve your application when the incoming request begins with your basename, so it shouldn't be an issue there.

Assuming that you're using `webpack-dev-server`, I don't actually know if there is a good way to simulate it being run from a non-root folder. You might be able to use the [`historyAPIFallback`](https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback) to rewrite URLs that begin with your pathname to your `index.html` file and all others to some 404 page.
