### ISSUE TITLE
history.push is changing url but not rendering component

### ISSUE THREAD

**Issue by kartikpandey2** [ReactTraining/history#732]
I am at route: `booking/get`
It renders search form. And when user clicks search button I am using this.props.history to push same url with new query parameter (`booking/get?test=10`).  But the problem is component is not rendering only url is changing.

![Without query param](https://user-images.githubusercontent.com/20434963/64116239-66d95200-cdaf-11e9-89d5-c59e19275e24.png)

After pushing url with query param using history.push

![With query param](https://user-images.githubusercontent.com/20434963/64116240-66d95200-cdaf-11e9-9229-43a18d7c722a.png)

**Comment by pshrmn** [comment]
There isn't enough information in your description to properly determine what the issue is. Can you put together a reproducible demo using [CodeSandbox](https://codesandbox.io/)?

If I had to guess, I would say that you somehow have multiple `history` instances and the one that you're pushing to isn't that same one that is attached to your router component.

**Comment by kartikpandey2** [comment]
@pshrmn  I have created demo, please check out https://codesandbox.io/s/sad-darwin-3pdz0?fontsize=14

There are 2 Routes.
*  `/search` (this.props.history.push is working)
* `/search/test` (this.props.history.push is not working)

How to reproduce - Navigate to above routes, fill in the input and click on the search button.

**Comment by pshrmn** [comment]
Your `Search2` component is re-rendering; you can see this by adding a `console.log` to its `render` function.

The issue that you are having is that you are setting state in `cDM`, but when you search, the `Search2` component isn't actually un/re-mounting, so the lifecycle method isn't called. 

The real issue is actually with the `Search` component being wrapped with an HoC inline. This is creating a new component every render, which causes unnecessary (un)mounts.

**Comment by kartikpandey2** [comment]
@pshrmn Now I am bit confused now.  Can you help me understand, what is the expected behavior when I push the same URL using history.push,  does react-router unmount component and remount it or it just calls render function again.
