### ISSUE TITLE
state missing while using hash history

### ISSUE THREAD

**Issue by brucewar** [ReactTraining/history#735]
When I use the following code with `createHashHistory` and then click browser back/forward, the state will be missing. How can I keep the state?
```js
history.push({
  pathname: '/xxx',
  state: { title: 'xxx' }
})
```

**Comment by pshrmn** [comment]
There is no `state` with the current hash history because it does not use the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API). Instead, it uses the browser's location API for navigation. The current version is more of a fallback for people building applications that need to target old browser. The next version of history will (I believe) only support more modern browsers, so it will have full `state` support.
