### ISSUE TITLE
Any way to pause listeners?

### ISSUE THREAD

**Issue by donysukardi** [ReactTraining/history#815]
I have a use case in a React application where I need to manipulate history stack by
- triggering `history.goBack`
- and then `history.replace` right after

However, I would like to bypass the listener for the first `history.goBack` call such that the route doesn't get rendered unnecessarily.

Public API doesn't seem to offer this kind of functionality. Would you be open to consider adding a capability to pause listeners?

**Comment by mjackson** [comment]
It should be pretty easy to do this using the public API. `history.listen` returns a function you can use to stop listening for new locations, so just surround your call to `goBack` with an `unlisten` followed by a `history.listen` call.

Otherwise, keep a variable around and just ignore the change yourself, like:

```js
let isPaused = false;
history.listen(location => {
  if (!isPaused) handleLocationChange(location);
});

function handleLocationChange(location) {
  // ...
}

// Somewhere in your app code
isPaused = true;
history.goBack();
isPaused = false;
history.replace();
```
