### ISSUE TITLE
Petition to re-open #570

### ISSUE THREAD

**Issue by juliancoleman** [ReactTraining/history#827]
There has been a long-standing issue going on 4 years about how this library will repeat `pushState` when navigating to the page the user is currently on. This is a nuisance to the user experience. That said, what would it take to get that PR merged and get this issue to bed? Even @mjackson agreed that it has been a nuisance.

The behavior of browser history is as follows:

```
User navigates to /page-1
User navigates to /page-2
User navigates to /page-2
The back button returns the user to /page-1, not /page-2
```

Re: #570

**Comment by mjackson** [comment]
`history.push` should not behave differently from `window.history.pushState`. If `pushState` adds a new location to the history stack (it does) then `history.push` should do the same thing. It's not this library's responsibility to make sure you aren't pushing duplicate URLs to the stack. That is the responsibility of code that uses this library.

For example, if you're using React Router v6 (currently in beta), the `<Link>` component [automatically detects if you're pushing to the same location and uses a replace instead of a push action](https://github.com/ReactTraining/react-router/blob/761f104ed144601b3bcd7a8a35aa635afc5e05db/packages/react-router-dom/index.tsx#L203-L206) to mimic what standard `<a>` elements do.

Hope that helps!
